# Generated by Django 5.1.5 on 2025-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hzcity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("house_name", models.CharField(max_length=128)),
                ("city_name", models.CharField(max_length=128)),
                ("localhost", models.CharField(max_length=128)),
                ("price", models.IntegerField()),
                ("type_name", models.CharField(max_length=128)),
                ("use_area", models.FloatField()),
                ("single_price", models.IntegerField()),
                ("forword", models.CharField(max_length=128)),
                ("floor", models.CharField(max_length=128)),
                ("fitment", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "city_hz",
            },
        ),
    ]
