# Generated by Django 5.1.5 on 2025-02-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="city",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "house_name",
                    models.CharField(
                        help_text="小区名称", max_length=128, verbose_name="小区名称"
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        help_text="所在市", max_length=128, verbose_name="所在市"
                    ),
                ),
                (
                    "localhost",
                    models.CharField(
                        help_text="具体位置", max_length=128, verbose_name="具体位置"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(help_text="房屋总价", verbose_name="房屋总价"),
                ),
                (
                    "type_name",
                    models.CharField(
                        help_text="户型", max_length=128, verbose_name="户型"
                    ),
                ),
                ("use_area", models.FloatField(help_text="占地", verbose_name="占地")),
                (
                    "single_price",
                    models.IntegerField(help_text="单价", verbose_name="单价"),
                ),
                (
                    "forword",
                    models.CharField(
                        help_text="朝向", max_length=128, verbose_name="朝向"
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        help_text="楼层", max_length=128, verbose_name="楼层"
                    ),
                ),
                (
                    "fitment",
                    models.CharField(
                        help_text="装修", max_length=128, verbose_name="装修"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="网址", max_length=128, verbose_name="网址"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="所在市", max_length=128, verbose_name="所在市"
                    ),
                ),
            ],
            options={
                "db_table": "city",
            },
        ),
        migrations.DeleteModel(
            name="hzcity",
        ),
    ]
