# Generated by Django 5.1.5 on 2025-02-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0002_city_delete_hzcity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, verbose_name="区域名称")),
                ("city_id", models.IntegerField(verbose_name="城市ID")),
            ],
            options={
                "db_table": "area_id",
            },
        ),
        migrations.CreateModel(
            name="city_id",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "city",
                    models.CharField(
                        help_text="城市", max_length=128, verbose_name="城市"
                    ),
                ),
            ],
            options={
                "db_table": "city_id",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        help_text="位置", max_length=128, verbose_name="位置"
                    ),
                ),
                ("area_id", models.IntegerField(help_text="区id", verbose_name="区id")),
            ],
            options={
                "db_table": "location_id",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="city",
            field=models.CharField(
                help_text="城市", max_length=128, verbose_name="城市"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="city_name",
            field=models.CharField(
                help_text="所在区", max_length=128, verbose_name="所在区"
            ),
        ),
    ]
