# Generated by Django 5.1.5 on 2025-02-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0003_area_city_id_location_alter_city_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="area_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="区域ID"),
        ),
        migrations.AddField(
            model_name="city",
            name="city_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="城市ID"),
        ),
        migrations.AddField(
            model_name="city",
            name="location_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="位置ID"),
        ),
    ]
