# Generated by Django 5.1.5 on 2025-02-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sysuser",
            table="sys_user",
        ),
    ]
